ruby_version: 2.4

format: progress

ignore:
  - "**/*":
      # Explicitly keep b/c these serve as documentation
      - Style/IfWithBooleanLiteralBranches
  - 'spec/**/*':
    - Lint/UselessAssignment
