# Test runner copied from R167/backblaze
name: Run tests
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
jobs:
  rspec:
    name: rspec ruby-${{ matrix.ruby }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ 2.4, 2.5, 2.6, 2.7 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      # Caching makes life better
      - name: build lockfile
        run: |
          bundle config path vendor/bundle
          bundle lock
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-
            bundle-use-ruby-${{ matrix.os }}-
      - name: install dependencies
        run: |
          bundle install --jobs 3 --retry 3
          bundle clean
      # Okay, back to what we really care about...
      - name: spec
        run:  bundle exec rake spec
